Feature/compose sample
rootstrap/FlowForms pull request #69
Opened 2023-09-15 18:50 UTC by ximenaperez

Please remember to add the proper labels to the PR. You can delete
the template sections that don't apply to this PR. Remove this message.

#### ISSUE[#59]
* closes #(59)

---

#### Description
* Add code sample for android compose

---

#### Tasks
* Add compose screen for login

---

#### Preview
![image](https://github.com/rootstrap/FlowForms/assets/5935015/1d85e65e-fc52-4862-ac0c-94d0cba61e67)

2023-09-18 14:36 UTC, hrodrick commented on exampleappandroidcompose/build.gradle.kts
Please review the module's name, try to keep the same naming style as the other modules: ExampleApp Android Compose

![image](https://github.com/rootstrap/FlowForms/assets/26490822/ce68d204-d2b7-42b4-bd8b-6e867075fe7f)

2023-09-18 14:36 UTC, hrodrick commented on exampleappandroidcompose/.gitignore
> +/build
Please add an empty line at the end of this file

2023-09-18 14:37 UTC, hrodrick commented on exampleappandroidcompose/build.gradle.kts
> +}
Please add an empty line at the end of this file

2023-09-18 14:38 UTC, hrodrick commented on exampleappandroidcompose/src/androidTest/java/com/example/exampleappandroidcompose/ExampleInstrumentedTest.kt
This file doesn't seem very useful, please remove

2023-09-18 14:39 UTC, hrodrick commented on exampleappandroidcompose/src/main/AndroidManifest.xml
> +</manifest>
Please add an empty line at the end of this file

2023-09-18 14:41 UTC, hrodrick commented on exampleappandroidcompose/src/main/java/com/example/exampleappandroidcompose/MainActivity.kt
> +import androidx.compose.foundation.layout.Row
I believe we don't need many of the imports here. Please use the `optimize imports` tool. I also recommend to enable it in the Android Studios' settings.
![image](https://github.com/rootstrap/FlowForms/assets/26490822/c733b2c8-c671-4ba4-a6e7-487c98693298)

2023-09-18 14:43 UTC, hrodrick commented on exampleappandroidcompose/src/main/java/com/example/exampleappandroidcompose/ui/screens/SignUpScreen.kt
> +}
Please add an empty line at the end of this file

2023-09-18 14:43 UTC, hrodrick commented on exampleappandroidcompose/src/main/java/com/example/exampleappandroidcompose/ui/theme/Color.kt
> +val Pink40 = Color(0xFF7D5260)
Same

2023-09-18 14:43 UTC, hrodrick commented on exampleappandroidcompose/src/main/java/com/example/exampleappandroidcompose/ui/theme/Dimension.kt
> +}
Same

2023-09-18 14:44 UTC, hrodrick commented on exampleappandroidcompose/src/main/java/com/example/exampleappandroidcompose/ui/theme/Type.kt
> +)
Same

2023-09-18 14:45 UTC, hrodrick commented on exampleappandroidcompose/src/main/res/values/colors.xml
> +</resources>
Same

2023-09-18 14:46 UTC, hrodrick commented on exampleappandroidcompose/src/main/res/values/strings.xml
> +</resources>
Same

2023-09-18 14:48 UTC, hrodrick commented on exampleappandroidcompose/src/main/res/values/strings.xml
> +    <string name="continue_btn">Continue</string>
Looks like this String is not used, please remove

2023-09-18 14:48 UTC, hrodrick commented on exampleappandroidcompose/src/main/res/values/themes.xml
> +</resources>
Please add an empty line at the end of this file

2023-09-18 14:49 UTC, hrodrick commented on exampleappandroidcompose/src/main/res/values/colors.xml
> +</resources>
It looks like these colors are not used, please remove

2023-09-18 14:49 UTC, hrodrick commented on exampleappandroidcompose/src/test/java/com/example/exampleappandroidcompose/ExampleUnitTest.kt
This file doesn't seem to be needed, please remove

2023-09-18 14:50 UTC, hrodrick requested changes
Nice work! Just left some comments

2023-09-19 12:49 UTC, hrodrick approved these changes

2023-09-20 19:43 UTC, marcossalto approved these changes
Well done! I left a couple of minor comments

2023-09-20 19:43 UTC, marcossalto commented on ExampleApp Android Compose/build.gradle.kts
> +    implementation(platform("androidx.compose:compose-bom:2022.10.00"))
I think we could move all of those hardcoded libraries to Dependencies object.

2023-09-20 19:43 UTC, marcossalto commented on ExampleApp Android Compose/proguard-rules.pro
> +#-renamesourcefileattribute SourceFile
Please add an empty line at EOF

2023-09-21 14:35 UTC, merged